// Name: Josue Cortez

#include <stdio.h>
#include <stdlib.h>
#include <unistd.h>
#include "sem.h"

Sem Produce;
Sem Consume;
int* buff = NULL;
int in = 0;
int out = 0;
int buffSize, numOfProducers, numOfConsumers, numOfExecutions;

void Producers(int producerID, int items);
void Consumers(int consumerID, int items);

void main()
{
    //int numOfThreads;
    int currentThreadID;
    char comma;

    ReadyQ = InitQueue();
    //printf("a\n");
    //scanf("%d%c%d", &numOfThreads, &comma, &numOfExecutions);
    scanf("%d%c%d%c%d%c%d", &buffSize, &comma, &numOfProducers, &comma, &numOfConsumers, &comma, &numOfExecutions);
    //printf("buffSize: %d\nnumOfProducers: %d\nnumOfConsumers: %d\nnumOfExecutions: %d\n", buffSize, numOfProducers, numOfConsumers, numOfExecutions);
    // if(numOfProducers + numOfConsumers <= 0) {
    //     printf("No Threads\n");
    //     return;
    // }
    
    buff = malloc(buffSize*sizeof(int));
    //printf("c\n");
    InitSem(&Produce, buffSize);
    InitSem(&Consume, 0);
    //printf("d\n");

    for(int i = 0; i < numOfProducers + numOfConsumers; i++) {
        //printf("i: %d\n", i);
        scanf("%d", &currentThreadID);
        //printf("ID: %d\n", currentThreadID);
        if(currentThreadID > 0){
            //printf("++");
            start_thread(Producers, currentThreadID, numOfExecutions);
            //printf("x");
            //start_thread(Producers, currentThreadID);
        }
        else if(currentThreadID <= 0){
            //printf("--");
            start_thread(Consumers, currentThreadID, numOfExecutions);
            //start_thread(Consumers, currentThreadID);
            //printf("y");
        }
        //printf("==");
    }
    //printf("e\n");
    run();
    //printf("end\n");
}

void Producers(int producerID, int items)
{
    // int item = 0;
    //printf("ID: %d\n", producerID);
    //printf("Items: %d \n", items);
    for (int i = 1; i <= items; i++){
        //printf("Prod\n");
        P(&Produce, producerID);
        //printf("buffIn: %d\n", buff[in]);
        if (!buff[in]){
            printf("\n Producer %d is producing item number %d \n", producerID, i);
            buff[in] = producerID;
            //printf("buffInIn: %d\n", buff[in]);
        }
        //printf("buffInOut: %d\n", buff[in]);
        in = (in + 1) % buffSize;
        //printf("H1\n");
        V(&Consume);
        //printf("pbfYield\n");
        yield();
        //printf("pYield\n");
    }

    TCB_t* deleted = DelQueue(ReadyQ);

    if(ReadyQ->head != NULL){
        swapcontext(&(deleted->context), &(ReadyQ->head->context));
    }
}

void Consumers(int consumerID, int items)
{
    for (int i = 1; i <= items; i++){
        P(&Consume, consumerID);
        // item = buff[out]
        if (buff[out]){
            printf("\n Consumer %d is consuming item generated by Producer %d \n", -consumerID, buff[out]);
            buff[out] = 0;
        }
        
        out = (out + 1) % buffSize;
        
        V(&Produce);
        //printf("vbfYield\n");
        yield();
        //printf("vYield\n");
    }

    TCB_t* deleted = DelQueue(ReadyQ);
    
    if(ReadyQ->head != NULL){
        swapcontext(&(deleted->context), &(ReadyQ->head->context));
    }
}
